"""Chapter 5, part 2: Two Clues at Once (September-October), puzzles 69-78.

All ten slots are 4 x 4 grids: four names, two plain categories and one
ordered (number) category. A bigger number is "more": more traps, a longer
bake, a higher summit, a higher price, more cords, more tickets, more
gallons, more candy.
Format: THEMES.md.  Story and cast: story/bible.md.
"""

THEMES = [
    # ------------------------------------------------------------------ 69
    {
        "slot": 69,
        "title": "The Lobster Trap Tally",
        "story": "Ask Nico about Tuesday's haul off Seal Ledge and the numbers grow with every telling, "
                 "along with the lobster, which is now the size of a wheelbarrow. Four skippers went out "
                 "that morning, each with a different bait and buoys of a different color. The lobster "
                 "co-op's tally sheet wants facts, not fish stories. Who used which bait and which buoys, "
                 "and how many traps did each skipper haul?",
        "entity": ["skipper", "skippers"],
        "cast": ["Nico"],
        "cats": [
            {"label": "Skipper", "kind": "name", "values": ["Arlo", "Yusuf", "Greta", "Nico"]},
            {"label": "Bait", "values": ["herring", "pogies", "redfish", "squid"],
             "ref": "the skipper who baited with {v}",
             "pred": "baited with {v}",
             "neg": "did not bait with {v}",
             "either": "baited with either {a} or {b}",
             "nor": "baited with neither {a} nor {b}",
             "short": "{v}"},
            {"label": "Buoy", "values": ["orange", "white", "purple", "lime"],
             "ref": "the skipper with {v} buoys",
             "pred": "had {v} buoys",
             "neg": "did not have {v} buoys",
             "either": "had either {a} or {b} buoys",
             "nor": "had neither {a} nor {b} buoys",
             "short": "the {v} buoys"},
            {"label": "Traps", "ordered": True, "nums": [20, 30, 40, 50],
             "ref": "the skipper who hauled {x} traps",
             "pred": "hauled {x} traps",
             "neg": "did not haul {x} traps",
             "either": "hauled either {a} or {b} traps",
             "nor": "hauled neither {a} nor {b} traps",
             "short": "{x} traps",
             "more": "hauled more traps than {y}",
             "less": "hauled fewer traps than {y}",
             "dmore": "hauled exactly {d} more than {y}",
             "dless": "hauled exactly {d} fewer than {y}",
             "dunit": ["trap", "traps"],
             "dmore1": "hauled exactly 10 more traps than {y}",
             "dless1": "hauled exactly 10 fewer traps than {y}"},
        ],
    },
    # ------------------------------------------------------------------ 70
    {
        "slot": 70,
        "title": "The Apple Pie Bake-Off",
        "story": "Rosa judged the apple pie bake-off at the Salt & Sugar Bakery, and four pies came out "
                 "of the ovens smelling like October itself. Each baker chose a different crust and a "
                 "different spice, and each pie spent a different time in the oven. Rosa wants the "
                 "secrets for her recipe box, and she has promised not to tell her sourdough starters. "
                 "Who made which crust, with which spice, and how long did each pie bake?",
        "entity": ["baker", "bakers"],
        "cast": ["Priya", "Rosa"],
        "cats": [
            {"label": "Baker", "kind": "name", "values": ["Priya", "Vito", "Imani", "Boris"]},
            {"label": "Crust", "values": ["lattice", "crumble", "plain", "braided"],
             "ref": "the baker with the {v} crust",
             "pred": "made a {v} crust",
             "neg": "did not make a {v} crust",
             "either": "made either a {a} or a {b} crust",
             "nor": "made neither a {a} nor a {b} crust",
             "short": "the {v} crust"},
            {"label": "Spice", "values": ["cinnamon", "nutmeg", "ginger", "cardamom"],
             "ref": "the baker who added {v}",
             "pred": "added {v}",
             "neg": "did not add {v}",
             "either": "added either {a} or {b}",
             "nor": "added neither {a} nor {b}",
             "short": "{v}"},
            {"label": "Bake", "ordered": True, "nums": [40, 45, 50, 55],
             "labels": ["40 minutes", "45 minutes", "50 minutes", "55 minutes"],
             "ref": "the baker whose pie baked {x}",
             "pred": "baked for {x}",
             "neg": "did not bake for {x}",
             "either": "baked for either {a} or {b}",
             "nor": "baked for neither {a} nor {b}",
             "short": "{x}",
             "more": "baked longer than {y}",
             "less": "baked for a shorter time than {y}",
             "dmore": "baked exactly {d} longer than {y}",
             "dless": "baked exactly {d} less than {y}",
             "dunit": ["minute", "minutes"],
             "dmore1": "baked exactly 5 minutes longer than {y}",
             "dless1": "baked exactly 5 minutes less than {y}"},
        ],
    },
    # ------------------------------------------------------------------ 71
    {
        "slot": 71,
        "title": "The Hiking Club Summits",
        "story": "Fall color peaked on the long October weekend, and four members of the hiking club "
                 "set off up four different hills. Wren whispered the whole way up hers, though there was "
                 "nobody to disturb but a chipmunk. Back at the trailhead, the club's logbook shows four "
                 "summit heights and not one name, and Felix calls that anything but shipshape. Who hiked "
                 "which hill, what did each pack for a snack, and how high did each one top out?",
        "entity": ["hiker", "hikers"],
        "cast": ["Felix", "Wren"],
        "cats": [
            {"label": "Hiker", "kind": "name", "values": ["Felix", "Wren", "Enzo", "Cass"]},
            {"label": "Hill", "values": ["Bramble Hill", "Crow's Nest", "Fiddler Hill", "Thimble Knob"],
             "ref": "the hiker on {v}",
             "pred": "hiked {v}",
             "neg": "did not hike {v}",
             "either": "hiked either {a} or {b}",
             "nor": "hiked neither {a} nor {b}",
             "short": "{v}"},
            {"label": "Snack", "values": ["trail mix", "jerky", "cheese", "figs"],
             "ref": "the hiker who packed {v}",
             "pred": "packed {v}",
             "neg": "did not pack {v}",
             "either": "packed either {a} or {b}",
             "nor": "packed neither {a} nor {b}",
             "short": "the {v}"},
            {"label": "Height", "ordered": True, "nums": [800, 1000, 1200, 1400],
             "labels": ["800 feet", "1,000 feet", "1,200 feet", "1,400 feet"],
             "ref": "the hiker who topped out at {x}",
             "pred": "topped out at {x}",
             "neg": "did not top out at {x}",
             "either": "topped out at either {a} or {b}",
             "nor": "topped out at neither {a} nor {b}",
             "short": "{x}",
             "more": "topped out higher than {y}",
             "less": "topped out lower than {y}",
             "dmore": "topped out exactly {d} higher than {y}",
             "dless": "topped out exactly {d} lower than {y}",
             "dunit": ["foot", "feet"],
             "dmore1": "topped out exactly 200 feet higher than {y}",
             "dless1": "topped out exactly 200 feet lower than {y}"},
        ],
    },
    # ------------------------------------------------------------------ 72
    {
        "slot": 72,
        "title": "The Gazette Ad Rates",
        "story": "Autumn is ad season at the Gazette, and four advertisers have bought space. "
                 "Lena's ad is the proudest of the lot: it announces the Keeper's Lamp's 150th-birthday "
                 "lighting at the Lantern Festival. Gus's sells rubber boots, because his knee says rain. "
                 "But every invoice went out wrong, and Ada would like them fixed before anyone pays "
                 "twice. Who chose which border, in which section, and what did each ad cost?",
        "entity": ["advertiser", "advertisers"],
        "cast": ["Gus", "Lena"],
        "cats": [
            {"label": "Advertiser", "kind": "name", "values": ["Gus", "Lena", "Tariq", "Olive"]},
            {"label": "Border", "values": ["plain", "dotted", "wavy", "rope"],
             "ref": "the advertiser with the {v} border",
             "pred": "chose a {v} border",
             "neg": "did not choose a {v} border",
             "either": "chose either a {a} or a {b} border",
             "nor": "chose neither a {a} nor a {b} border",
             "short": "the {v} border"},
            {"label": "Section", "values": ["sports", "recipes", "tides", "puzzles"],
             "ref": "the advertiser in the {v} section",
             "pred": "ran an ad in the {v} section",
             "neg": "did not run an ad in the {v} section",
             "either": "ran an ad in either the {a} or the {b} section",
             "nor": "ran an ad in neither the {a} nor the {b} section",
             "short": "the {v} section"},
            {"label": "Price", "ordered": True, "nums": [10, 20, 30, 40],
             "labels": ["$10", "$20", "$30", "$40"],
             "ref": "the advertiser who paid {x}",
             "pred": "paid {x}",
             "neg": "did not pay {x}",
             "either": "paid either {a} or {b}",
             "nor": "paid neither {a} nor {b}",
             "short": "{x}",
             "more": "paid more than {y}",
             "less": "paid less than {y}",
             "dmore": "paid exactly {d} more than {y}",
             "dless": "paid exactly {d} less than {y}",
             "dunit": ["dollar", "dollars"],
             "dmore1": "paid exactly 10 dollars more than {y}",
             "dless1": "paid exactly 10 dollars less than {y}"},
        ],
    },
    # ------------------------------------------------------------------ 73
    {
        "slot": 73,
        "title": "The Lamp Fund Jar",
        "story": "Since spring, the Keeper's Lamp fund jar has sat by the register at Mahoney's, "
                 "collecting for the lamp's 150th-birthday celebration. One October afternoon four donors "
                 "fed it, each tucking a little note in with the money. Gus counted it all in a hurry, "
                 "and now the notes and the gifts are hopelessly shuffled. The Gazette wants to thank "
                 "each donor properly. Who gave how much, how did each one pay, and who left which note?",
        "entity": ["donor", "donors"],
        "cast": ["Lena", "Jonah", "Gus"],
        "cats": [
            {"label": "Donor", "kind": "name", "values": ["Lena", "Jonah", "Tova", "Gus"]},
            {"label": "Paid", "values": ["check", "cash", "coin", "money order"],
             "ref": "the donor who paid by {v}",
             "pred": "paid by {v}",
             "neg": "did not pay by {v}",
             "either": "paid by either {a} or {b}",
             "nor": "paid by neither {a} nor {b}",
             "short": "{v}"},
            {"label": "Note", "values": ["poem", "drawing", "thank-you", "riddle"],
             "ref": "the donor who left a {v}",
             "pred": "left a {v}",
             "neg": "did not leave a {v}",
             "either": "left either a {a} or a {b}",
             "nor": "left neither a {a} nor a {b}",
             "short": "the {v}"},
            {"label": "Gift", "ordered": True, "nums": [25, 50, 75, 100],
             "labels": ["$25", "$50", "$75", "$100"],
             "ref": "the donor who gave {x}",
             "pred": "gave {x}",
             "neg": "did not give {x}",
             "either": "gave either {a} or {b}",
             "nor": "gave neither {a} nor {b}",
             "short": "{x}",
             "more": "gave more than {y}",
             "less": "gave less than {y}",
             "dmore": "gave exactly {d} more than {y}",
             "dless": "gave exactly {d} less than {y}",
             "dunit": ["dollar", "dollars"],
             "dmore1": "gave exactly 25 dollars more than {y}",
             "dless1": "gave exactly 25 dollars less than {y}"},
        ],
    },
    # ------------------------------------------------------------------ 74
    {
        "slot": 74,
        "title": "The Firewood Orders",
        "story": "When the first cold snap hit, four households on Hattie's lane wanted firewood, so she "
                 "took every order on one of her lists. That list is now somewhere on another list, "
                 "possibly clipped to a third. The wood came Saturday, every neighbor had a load stacked "
                 "by Sunday night, and the woodcutter's bill still needs checking. Who chose which wood, "
                 "how many cords did each neighbor order, and where was each load stacked?",
        "entity": ["neighbor", "neighbors"],
        "cast": ["Hattie"],
        "cats": [
            {"label": "Neighbor", "kind": "name", "values": ["Kit", "Hattie", "Ruben", "Amara"]},
            {"label": "Wood", "values": ["oak", "birch", "maple", "ash"],
             "ref": "the neighbor who chose {v}",
             "pred": "chose {v}",
             "neg": "did not choose {v}",
             "either": "chose either {a} or {b}",
             "nor": "chose neither {a} nor {b}",
             "short": "the {v}"},
            {"label": "Stacked", "values": ["porch", "shed", "barn", "garage"],
             "ref": "the neighbor with the woodpile by the {v}",
             "pred": "stacked the wood by the {v}",
             "neg": "did not stack the wood by the {v}",
             "either": "stacked the wood by either the {a} or the {b}",
             "nor": "stacked the wood by neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Cords", "ordered": True, "nums": [1, 2, 3, 4],
             "labels": ["1 cord", "2 cords", "3 cords", "4 cords"],
             "ref": "the neighbor who ordered {x}",
             "pred": "ordered {x}",
             "neg": "did not order {x}",
             "either": "ordered either {a} or {b}",
             "nor": "ordered neither {a} nor {b}",
             "short": "{x}",
             "more": "ordered more wood than {y}",
             "less": "ordered less wood than {y}",
             "dmore": "ordered exactly {d} more than {y}",
             "dless": "ordered exactly {d} less than {y}",
             "dunit": ["cord", "cords"],
             "dmore1": "ordered exactly 1 cord more than {y}",
             "dless1": "ordered exactly 1 cord less than {y}"},
        ],
    },
    # ------------------------------------------------------------------ 75
    {
        "slot": 75,
        "title": "The Harvest Shuttle Fares",
        "story": "Twice an hour on harvest weekend, a hay wagon rattles from Main Street to Hilltop "
                 "Orchard's fields. Four riders paid different fares to different stops, and each rode "
                 "home with an armful from the market barn, Teddy with his camera perched on top of his. "
                 "Now the fare can is a dollar off, and the farmer wants it to balance before the next "
                 "run. Where did each rider go, what did each carry home, and what did each pay?",
        "entity": ["rider", "riders"],
        "cast": ["Teddy"],
        "cats": [
            {"label": "Rider", "kind": "name", "values": ["Teddy", "Basil", "Nadia", "Zeke"]},
            {"label": "Stop", "values": ["corn maze", "cider stand", "orchard gate", "farm stand"],
             "ref": "the rider bound for the {v}",
             "pred": "rode to the {v}",
             "neg": "did not ride to the {v}",
             "either": "rode to either the {a} or the {b}",
             "nor": "rode to neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Carried", "values": ["pumpkin", "apple crate", "cider jug", "mums"],
             "ref": "the rider with the {v}",
             "pred": "carried home the {v}",
             "neg": "did not carry home the {v}",
             "either": "carried home either the {a} or the {b}",
             "nor": "carried home neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Fare", "ordered": True, "nums": [3, 5, 7, 9],
             "labels": ["$3", "$5", "$7", "$9"],
             "ref": "the rider who paid {x}",
             "pred": "paid {x}",
             "neg": "did not pay {x}",
             "either": "paid either {a} or {b}",
             "nor": "paid neither {a} nor {b}",
             "short": "the {x} fare",
             "more": "paid a higher fare than {y}",
             "less": "paid a lower fare than {y}",
             "dmore": "paid exactly {d} more than {y}",
             "dless": "paid exactly {d} less than {y}",
             "dunit": ["dollar", "dollars"],
             "dmore1": "paid exactly 2 dollars more than {y}",
             "dless1": "paid exactly 2 dollars less than {y}"},
        ],
    },
    # ------------------------------------------------------------------ 76
    {
        "slot": 76,
        "title": "The Quilt Raffle",
        "story": "Hattie hung four quilts across the church hall stage for the fall raffle, each a "
                 "year's work by the sewing circle. Four hopefuls bought tickets, each for a different "
                 "quilt and with a different room already picked out for it. Wren, for one, whispers that "
                 "she has measured twice. Before the drawing, Hattie wants every stub checked against her "
                 "list. Who entered for which quilt, how many tickets did each buy, and which room did "
                 "each have in mind?",
        "entity": ["entrant", "entrants"],
        "cast": ["Wren", "Hattie"],
        "cats": [
            {"label": "Entrant", "kind": "name", "values": ["Emil", "Wren", "Jade", "Pablo"]},
            {"label": "Quilt", "values": ["log cabin", "star", "nine patch", "wedding ring"],
             "ref": "the entrant for the {v} quilt",
             "pred": "entered for the {v} quilt",
             "neg": "did not enter for the {v} quilt",
             "either": "entered for either the {a} or the {b} quilt",
             "nor": "entered for neither the {a} nor the {b} quilt",
             "short": "the {v} quilt"},
            {"label": "Wants it for", "values": ["bedroom", "den", "porch", "guest room"],
             "ref": "the entrant with the {v} in mind",
             "pred": "had the {v} in mind",
             "neg": "did not have the {v} in mind",
             "either": "had either the {a} or the {b} in mind",
             "nor": "had neither the {a} nor the {b} in mind",
             "short": "the {v}"},
            {"label": "Tickets", "ordered": True, "nums": [2, 4, 6, 8],
             "ref": "the entrant with {x} tickets",
             "pred": "bought {x} tickets",
             "neg": "did not buy {x} tickets",
             "either": "bought either {a} or {b} tickets",
             "nor": "bought neither {a} nor {b} tickets",
             "short": "{x} tickets",
             "more": "bought more tickets than {y}",
             "less": "bought fewer tickets than {y}",
             "dmore": "bought exactly {d} more than {y}",
             "dless": "bought exactly {d} fewer than {y}",
             "dunit": ["ticket", "tickets"],
             "dmore1": "bought exactly 2 more tickets than {y}",
             "dless1": "bought exactly 2 fewer tickets than {y}"},
        ],
    },
    # ------------------------------------------------------------------ 77
    {
        "slot": 77,
        "title": "The Cider Press Batches",
        "story": "Come October, Felix wheels the old cider press out of the boatyard's paint shed and "
                 "lends it to the neighbors for a fair share of each batch. This year four pressed, Felix "
                 "included, each with a different apple mix and a hand-drawn label for the jugs. Nobody "
                 "wrote down the gallons, and a fair share needs numbers. Who pressed which mix, who "
                 "drew which label, and how much cider did each one make?",
        "entity": ["neighbor", "neighbors"],
        "cast": ["Priya", "Felix"],
        "cats": [
            {"label": "Neighbor", "kind": "name", "values": ["Marta", "Priya", "Cyrus", "Felix"]},
            {"label": "Mix", "values": ["tart", "sweet", "spicy", "wild"],
             "ref": "the neighbor with the {v} mix",
             "pred": "pressed a {v} mix",
             "neg": "did not press a {v} mix",
             "either": "pressed either a {a} or a {b} mix",
             "nor": "pressed neither a {a} nor a {b} mix",
             "short": "the {v} mix"},
            {"label": "Label", "values": ["owl", "anchor", "moon", "star"],
             "ref": "the neighbor with the {v} label",
             "pred": "drew the {v} label",
             "neg": "did not draw the {v} label",
             "either": "drew either the {a} or the {b} label",
             "nor": "drew neither the {a} nor the {b} label",
             "short": "the {v} label"},
            {"label": "Gallons", "ordered": True, "nums": [5, 10, 15, 20],
             "labels": ["5 gallons", "10 gallons", "15 gallons", "20 gallons"],
             "ref": "the neighbor who made {x}",
             "pred": "made {x} of cider",
             "neg": "did not make {x} of cider",
             "either": "made either {a} or {b} of cider",
             "nor": "made neither {a} nor {b} of cider",
             "short": "{x}",
             "more": "made more cider than {y}",
             "less": "made less cider than {y}",
             "dmore": "made exactly {d} more than {y}",
             "dless": "made exactly {d} less than {y}",
             "dunit": ["gallon", "gallons"],
             "dmore1": "made exactly 5 gallons more than {y}",
             "dless1": "made exactly 5 gallons less than {y}"},
        ],
    },
    # ------------------------------------------------------------------ 78
    {
        "slot": 78,
        "title": "The Costume Parade",
        "story": "Candy rained on Main Street as the Halloween parade closed out October. Four grown-ups "
                 "marched in costume, each handing out a different sweet from a different-sized bag, and "
                 "every last piece was gone by the bandstand. Ada wants the counts for Thursday's "
                 "write-up. \"The Gazette prints numbers, not guesses,\" she says. Who wore which "
                 "costume, who brought which candy, and how many pieces did each one hand out?",
        "entity": ["marcher", "marchers"],
        "cast": ["Mabel", "Otis"],
        "cats": [
            {"label": "Marcher", "kind": "name", "values": ["Mabel", "Otis", "Hugo", "Dot"]},
            {"label": "Costume", "values": ["pirate", "mermaid", "scarecrow", "robot"],
             "ref": "the {v}",
             "pred": "dressed as a {v}",
             "neg": "did not dress as a {v}",
             "either": "dressed as either a {a} or a {b}",
             "nor": "dressed as neither a {a} nor a {b}",
             "short": "the {v} costume"},
            {"label": "Candy", "values": ["taffy", "caramels", "licorice", "gumdrops"],
             "ref": "the marcher with the {v}",
             "pred": "brought {v}",
             "neg": "did not bring {v}",
             "either": "brought either {a} or {b}",
             "nor": "brought neither {a} nor {b}",
             "short": "the {v}"},
            {"label": "Handed out", "ordered": True, "nums": [50, 75, 100, 125],
             "labels": ["50 pieces", "75 pieces", "100 pieces", "125 pieces"],
             "ref": "the marcher who handed out {x}",
             "pred": "handed out {x}",
             "neg": "did not hand out {x}",
             "either": "handed out either {a} or {b}",
             "nor": "handed out neither {a} nor {b}",
             "short": "{x}",
             "more": "handed out more candy than {y}",
             "less": "handed out less candy than {y}",
             "dmore": "handed out exactly {d} more than {y}",
             "dless": "handed out exactly {d} fewer than {y}",
             "dunit": ["piece", "pieces"],
             "dmore1": "handed out exactly 25 more pieces than {y}",
             "dless1": "handed out exactly 25 fewer pieces than {y}"},
        ],
    },
]
