"""Chapter 6, part 1: Case Files (November), puzzles 79-87.

Five-suspect cases: five names plus three categories, one of them ordered
(a time, an age or a weekday). 79-86 are case54 grids; 87 is the chapter's
first "Suppose" puzzle. Every theme carries a whodunit "question"; the
culprit is whoever holds the question's value. Only #84 forces its answer
(Teddy borrowed the spare key for his photo series; see the bible's threads).
Format: THEMES.md.  Story and cast: story/bible.md, section 6.
"""

THEMES = [
    # ------------------------------------------------------------------ 79
    {
        "slot": 79,
        "title": "The Case of the Pie Server",
        "story": "Sixty years of church suppers, and Hattie's grandmother's silver pie server had never "
                 "gone astray. Then came the early-November pie auction, where the town orders its "
                 "Thanksgiving pies, and somewhere between bids it vanished. Five helpers each baked one "
                 "pie, arrived at a different time and worked a different spot. The server turned up that "
                 "night in a coat in the cloakroom, and only the cloakroom helper had handled the coats. "
                 "Who slipped the pie server into a coat pocket?",
        "entity": ["helper", "helpers"],
        "cast": ["Rosa", "Gus", "Hattie"],
        "question": {"text": "Who slipped the pie server into a coat pocket?",
                     "cat": "Spot", "value": "cloakroom"},
        "cats": [
            {"label": "Helper", "kind": "name", "values": ["Rosa", "Gus", "Della", "Vito", "Imani"]},
            {"label": "Pie", "values": ["pecan", "pumpkin", "apple", "mince", "cherry"],
             "ref": "the {v} pie's baker",
             "pred": "baked the {v} pie",
             "neg": "did not bake the {v} pie",
             "either": "baked either the {a} or the {b} pie",
             "nor": "baked neither the {a} nor the {b} pie",
             "short": "the {v} pie"},
            {"label": "Spot", "values": ["kitchen", "stage", "cloakroom", "porch", "bake table"],
             "ref": "the {v} helper",
             "pred": "worked the {v}",
             "neg": "did not work the {v}",
             "either": "worked either the {a} or the {b}",
             "nor": "worked neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Time", "ordered": True,
             "nums": [1080, 1095, 1110, 1125, 1140],
             "labels": ["6:00 p.m.", "6:15 p.m.", "6:30 p.m.", "6:45 p.m.", "7:00 p.m."],
             "ref": "the helper who arrived at {x}",
             "pred": "arrived at {x}",
             "neg": "did not arrive at {x}",
             "either": "arrived at either {a} or {b}",
             "nor": "arrived at neither {a} nor {b}",
             "short": "{x}",
             "more": "arrived later than {y}",
             "less": "arrived earlier than {y}",
             "dmore": "arrived exactly {d} after {y}",
             "dless": "arrived exactly {d} before {y}",
             "dunit": ["minute", "minutes"],
             "dmore1": "arrived 15 minutes after {y}",
             "dless1": "arrived 15 minutes before {y}"},
        ],
    },
    # ------------------------------------------------------------------ 80
    {
        "slot": 80,
        "title": "The Case of the Loose Mooring",
        "story": "Frost silvered the town pier one November morning, the week before haul-out, when "
                 "someone untied Felix's sailboat, the Ripple, and let her drift onto Gull Rock. She has a "
                 "scraped keel; Felix has a long face. Five early risers came down to the dock, each "
                 "at a different time, in a different coat, on a different errand. A dog walker on the "
                 "seawall saw someone in a yellow slicker bent over the Ripple's mooring "
                 "line. Who untied the Ripple?",
        "entity": ["early riser", "early risers"],
        "cast": ["Nico", "Felix"],
        "question": {"text": "Who untied the Ripple?", "cat": "Coat", "value": "slicker"},
        "cats": [
            {"label": "Early riser", "kind": "name", "values": ["Walt", "Quinn", "Bea", "Nico", "Hal"]},
            {"label": "Coat", "values": ["slicker", "peacoat", "parka", "barn coat", "fleece"],
             "ref": "the person in the {v}",
             "pred": "wore the {v}",
             "neg": "did not wear the {v}",
             "either": "wore either the {a} or the {b}",
             "nor": "wore neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Errand", "values": ["bait", "mail", "coffee", "ice", "diesel"],
             "ref": "the person who came for {v}",
             "pred": "came for {v}",
             "neg": "did not come for {v}",
             "either": "came for either {a} or {b}",
             "nor": "came for neither {a} nor {b}",
             "short": "the {v} errand"},
            {"label": "Time", "ordered": True,
             "nums": [360, 390, 420, 450, 480],
             "labels": ["6:00 a.m.", "6:30 a.m.", "7:00 a.m.", "7:30 a.m.", "8:00 a.m."],
             "ref": "the person who arrived at {x}",
             "pred": "arrived at {x}",
             "neg": "did not arrive at {x}",
             "either": "arrived at either {a} or {b}",
             "nor": "arrived at neither {a} nor {b}",
             "short": "{x}",
             "more": "arrived later than {y}",
             "less": "arrived earlier than {y}",
             "dmore": "arrived exactly {d} after {y}",
             "dless": "arrived exactly {d} before {y}",
             "dunit": ["minute", "minutes"],
             "dmore1": "arrived half an hour after {y}",
             "dless1": "arrived half an hour before {y}"},
        ],
    },
    # ------------------------------------------------------------------ 81
    {
        "slot": 81,
        "title": "The Case of the Recipe Card",
        "story": "Rosa's great-grandmother's cranberry bread recipe, in faded pencil on a card, has hung "
                 "on the bakery corkboard for years. On Saturday morning it vanished, and Rosa swears even "
                 "Gloria, her sourdough starter, looks worried. Five customers came in that morning, each "
                 "at a different time, each ordering something different and sitting somewhere "
                 "different. The corkboard hangs right beside the window table, out of reach of every "
                 "other seat. Who pocketed the recipe card?",
        "entity": ["customer", "customers"],
        "cast": ["Priya", "Mabel", "Rosa"],
        "question": {"text": "Who pocketed the recipe card?", "cat": "Seat", "value": "window"},
        "cats": [
            {"label": "Customer", "kind": "name", "values": ["Selma", "Priya", "Kenji", "Lou", "Mabel"]},
            {"label": "Order", "values": ["muffin", "scone", "bagel", "croissant", "danish"],
             "ref": "the customer with the {v}",
             "pred": "ordered the {v}",
             "neg": "did not order the {v}",
             "either": "ordered either the {a} or the {b}",
             "nor": "ordered neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Seat", "values": ["window", "counter", "corner", "patio", "booth"],
             "ref": "the customer in the {v} seat",
             "pred": "took the {v} seat",
             "neg": "did not take the {v} seat",
             "either": "took either the {a} or the {b} seat",
             "nor": "took neither the {a} nor the {b} seat",
             "short": "the {v} seat"},
            {"label": "Time", "ordered": True,
             "nums": [420, 450, 480, 510, 540],
             "labels": ["7:00 a.m.", "7:30 a.m.", "8:00 a.m.", "8:30 a.m.", "9:00 a.m."],
             "ref": "the customer who came in at {x}",
             "pred": "came in at {x}",
             "neg": "did not come in at {x}",
             "either": "came in at either {a} or {b}",
             "nor": "came in at neither {a} nor {b}",
             "short": "{x}",
             "more": "came in later than {y}",
             "less": "came in earlier than {y}",
             "dmore": "came in exactly {d} after {y}",
             "dless": "came in exactly {d} before {y}",
             "dunit": ["minute", "minutes"],
             "dmore1": "came in half an hour after {y}",
             "dless1": "came in half an hour before {y}"},
        ],
    },
    # ------------------------------------------------------------------ 82
    {
        "slot": 82,
        "title": "The Case of the Copper Whale",
        "story": "For as long as anyone can remember, a copper whale has swung on the boatyard roof. On "
                 "Wednesday morning the roof was bare, and Felix called it the least shipshape thing he "
                 "had ever seen. Five visitors were in the yard the evening before, each with a different "
                 "tool and a different excuse. The roof is too high to reach without a ladder, and fresh "
                 "ladder marks dent the frost under the eaves. Who took down the copper whale?",
        "entity": ["visitor", "visitors"],
        "cast": ["Felix"],
        "question": {"text": "Who took down the copper whale?", "cat": "Tool", "value": "ladder"},
        "cats": [
            {"label": "Visitor", "kind": "name", "values": ["Jade", "Arlo", "Boris", "Cass", "Milo"]},
            {"label": "Tool", "values": ["ladder", "rope", "wrench", "lantern", "crowbar"],
             "ref": "the visitor with the {v}",
             "pred": "carried the {v}",
             "neg": "did not carry the {v}",
             "either": "carried either the {a} or the {b}",
             "nor": "carried neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Excuse", "values": ["fishing", "jogging", "sketching", "lost dog", "stargazing"],
             "ref": "the visitor with the {v} excuse",
             "pred": "gave the {v} excuse",
             "neg": "did not give the {v} excuse",
             "either": "gave either the {a} or the {b} excuse",
             "nor": "gave neither the {a} nor the {b} excuse",
             "short": "the {v} excuse"},
            {"label": "Age", "ordered": True,
             "nums": [20, 30, 40, 50, 60],
             "ref": "the {x}-year-old",
             "pred": "is {x} years old",
             "neg": "is not {x} years old",
             "either": "is either {a} or {b} years old",
             "nor": "is neither {a} nor {b} years old",
             "short": "age {x}",
             "more": "is older than {y}",
             "less": "is younger than {y}",
             "dmore": "is exactly {d} older than {y}",
             "dless": "is exactly {d} younger than {y}",
             "dunit": ["year", "years"],
             "dmore1": "is 10 years older than {y}",
             "dless1": "is 10 years younger than {y}"},
        ],
    },
    # ------------------------------------------------------------------ 83
    {
        "slot": 83,
        "title": "The Case of the Crossword",
        "story": "The night before press day, someone changed three answers in Ada's crossword, and the "
                 "Gazette came within one proofread of printing GULL as a kind of cheese. Five visitors "
                 "used the puzzle desk that evening, each at a different time, with a different pen and a "
                 "different snack. Inkwell the cat was a suspect for about a minute. All three changes "
                 "are in green ink. Who scrambled the crossword?",
        "entity": ["visitor", "visitors"],
        "cast": ["Otis", "Wren"],
        "question": {"text": "Who scrambled the crossword?", "cat": "Pen", "value": "green"},
        "cats": [
            {"label": "Visitor", "kind": "name", "values": ["Otis", "Faye", "Emil", "Tariq", "Wren"]},
            {"label": "Pen", "values": ["green", "red", "blue", "black", "purple"],
             "ref": "the visitor with the {v} pen",
             "pred": "carried the {v} pen",
             "neg": "did not carry the {v} pen",
             "either": "carried either the {a} or the {b} pen",
             "nor": "carried neither the {a} nor the {b} pen",
             "short": "the {v} pen"},
            {"label": "Snack", "values": ["pretzels", "fudge", "grapes", "popcorn", "almonds"],
             "ref": "the visitor who brought {v}",
             "pred": "brought {v}",
             "neg": "did not bring {v}",
             "either": "brought either {a} or {b}",
             "nor": "brought neither {a} nor {b}",
             "short": "the {v}"},
            {"label": "Time", "ordered": True,
             "nums": [1020, 1050, 1080, 1110, 1140],
             "labels": ["5:00 p.m.", "5:30 p.m.", "6:00 p.m.", "6:30 p.m.", "7:00 p.m."],
             "ref": "the visitor who stopped by at {x}",
             "pred": "stopped by at {x}",
             "neg": "did not stop by at {x}",
             "either": "stopped by at either {a} or {b}",
             "nor": "stopped by at neither {a} nor {b}",
             "short": "{x}",
             "more": "stopped by later than {y}",
             "less": "stopped by earlier than {y}",
             "dmore": "stopped by exactly {d} after {y}",
             "dless": "stopped by exactly {d} before {y}",
             "dunit": ["minute", "minutes"],
             "dmore1": "stopped by half an hour after {y}",
             "dless1": "stopped by half an hour before {y}"},
        ],
    },
    # ------------------------------------------------------------------ 84
    {
        "slot": 84,
        "title": "The Case of the Wandering Key",
        "story": "Otis keeps the spare lighthouse key on a hook in the harbor office. One November "
                 "Thursday the hook sat empty, and by Friday morning the key was quietly back, as if it "
                 "had never left. Five people visited the office that Thursday, each at a different hour, "
                 "on a different errand, standing in a different spot. The hook is on the key wall, and "
                 "only someone at that wall could have lifted the key unseen. Who borrowed the spare key?",
        "entity": ["visitor", "visitors"],
        "cast": ["Lena", "Gus", "Teddy", "Otis"],
        "question": {"text": "Who borrowed the spare key?", "cat": "Spot", "value": "key wall"},
        "answer": "Teddy",
        # Teddy wanted the key for low-tide photos at the Point, so his errand is the tide chart.
        "answer_has": {"Visit": "tide chart"},
        "cats": [
            {"label": "Visitor", "kind": "name", "values": ["Lena", "Gus", "Nadia", "Teddy", "Sam"]},
            {"label": "Visit", "values": ["tide chart", "mooring fee", "lost cap", "radio", "permit"],
             "ref": "the visitor who asked about the {v}",
             "pred": "asked about the {v}",
             "neg": "did not ask about the {v}",
             "either": "asked about either the {a} or the {b}",
             "nor": "asked about neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Spot", "values": ["key wall", "desk", "window", "map table", "stove"],
             "ref": "the visitor by the {v}",
             "pred": "stood by the {v}",
             "neg": "did not stand by the {v}",
             "either": "stood by either the {a} or the {b}",
             "nor": "stood by neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Time", "ordered": True,
             "nums": [9, 10, 11, 12, 13],
             "labels": ["9:00 a.m.", "10:00 a.m.", "11:00 a.m.", "noon", "1:00 p.m."],
             "ref": "the visitor who came in at {x}",
             "pred": "came in at {x}",
             "neg": "did not come in at {x}",
             "either": "came in at either {a} or {b}",
             "nor": "came in at neither {a} nor {b}",
             "short": "{x}",
             "more": "came in later than {y}",
             "less": "came in earlier than {y}",
             "dmore": "came in exactly {d} after {y}",
             "dless": "came in exactly {d} before {y}",
             "dunit": ["hour", "hours"],
             "dmore1": "came in an hour after {y}",
             "dless1": "came in an hour before {y}"},
        ],
    },
    # ------------------------------------------------------------------ 85
    {
        "slot": 85,
        "title": "The Case of the Silent Bell",
        "story": "On the Sunday before Thanksgiving, the bell ringer at St. Brendan's heaved on the rope "
                 "and got nothing but a soft thump: someone had wrapped the clapper in a wool scarf. The "
                 "tower sign-in sheet (Hattie's idea, naturally) lists five climbers that week, each on a "
                 "different weekday, each with a different scarf and a different reason. The scarf on the "
                 "clapper is cable-knit. Who muffled the bell?",
        "entity": ["climber", "climbers"],
        "cast": ["Hattie"],
        "question": {"text": "Who muffled the bell?", "cat": "Scarf", "value": "cable"},
        "cats": [
            {"label": "Climber", "kind": "name", "values": ["Tova", "Linus", "Hattie", "Gideon", "Pablo"]},
            {"label": "Scarf", "values": ["striped", "plaid", "argyle", "red", "cable"],
             "ref": "the climber in the {v} scarf",
             "pred": "wore the {v} scarf",
             "neg": "did not wear the {v} scarf",
             "either": "wore either the {a} or the {b} scarf",
             "nor": "wore neither the {a} nor the {b} scarf",
             "short": "the {v} scarf"},
            {"label": "Reason", "values": ["dusting", "repairs", "bats", "the view", "pigeons"],
             "ref": "the climber with {v} in mind",
             "pred": "went up with {v} in mind",
             "neg": "did not go up with {v} in mind",
             "either": "went up with either {a} or {b} in mind",
             "nor": "went up with neither {a} nor {b} in mind",
             "short": "{v}"},
            {"label": "Day", "ordered": True,
             "nums": [1, 2, 3, 4, 5],
             "labels": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
             "ref": "the {x} climber",
             "pred": "went up on {x}",
             "neg": "did not go up on {x}",
             "either": "went up on either {a} or {b}",
             "nor": "went up on neither {a} nor {b}",
             "short": "{x}",
             "more": "went up later in the week than {y}",
             "less": "went up earlier in the week than {y}",
             "dmore": "went up exactly {d} after {y}",
             "dless": "went up exactly {d} before {y}",
             "dunit": ["day", "days"],
             "dmore1": "went up the day after {y}",
             "dless1": "went up the day before {y}"},
        ],
    },
    # ------------------------------------------------------------------ 86
    {
        "slot": 86,
        "title": "The Case of the Muddy Bootprints",
        "story": "Wren stepped out for lunch on Tuesday and came back to a trail of mud across the "
                 "library's freshly waxed floor, and a soggy book about whales on the returns cart. Five "
                 "patrons came by that afternoon, each at a different time, in different boots, bound for "
                 "a different section. The prints have the deep ridged tread of rubber boots. \"Mud,\" "
                 "Wren whispers, \"on my wax.\" Who tracked in the mud?",
        "entity": ["patron", "patrons"],
        "cast": ["Nico", "Wren"],
        "question": {"text": "Who tracked in the mud?", "cat": "Boots", "value": "rubber"},
        "cats": [
            {"label": "Patron", "kind": "name", "values": ["Pearl", "Nico", "Milo", "Greta", "Oscar"]},
            {"label": "Boots", "values": ["rubber", "hiking", "cowboy", "snow", "work"],
             "ref": "the patron in {v} boots",
             "pred": "wore {v} boots",
             "neg": "did not wear {v} boots",
             "either": "wore either {a} or {b} boots",
             "nor": "wore neither {a} nor {b} boots",
             "short": "the {v} boots"},
            {"label": "Section", "values": ["maps", "history", "cooking", "travel", "poetry"],
             "ref": "the patron in the {v} section",
             "pred": "browsed the {v} section",
             "neg": "did not browse the {v} section",
             "either": "browsed either the {a} or the {b} section",
             "nor": "browsed neither the {a} nor the {b} section",
             "short": "the {v} section"},
            {"label": "Time", "ordered": True,
             "nums": [780, 810, 840, 870, 900],
             "labels": ["1:00 p.m.", "1:30 p.m.", "2:00 p.m.", "2:30 p.m.", "3:00 p.m."],
             "ref": "the patron who came by at {x}",
             "pred": "came by at {x}",
             "neg": "did not come by at {x}",
             "either": "came by at either {a} or {b}",
             "nor": "came by at neither {a} nor {b}",
             "short": "{x}",
             "more": "came by later than {y}",
             "less": "came by earlier than {y}",
             "dmore": "came by exactly {d} after {y}",
             "dless": "came by exactly {d} before {y}",
             "dunit": ["minute", "minutes"],
             "dmore1": "came by half an hour after {y}",
             "dless1": "came by half an hour before {y}"},
        ],
    },
    # ------------------------------------------------------------------ 87
    {
        "slot": 87,
        "title": "The Case of the Vanishing Cameo",
        "story": "Thanksgiving afternoon at the Gull's Rest Inn: the turkey was resting, and so were the "
                 "guests. Then Priya's heirloom cameo brooch vanished, velvet pouch and all, from the "
                 "parlor mantel. Five guests had settled in the parlor, each at a different time, with a "
                 "different drink and a different book from the shelf. The pouch turned up, empty, tucked "
                 "inside the parlor's almanac. Who tucked the cameo away?",
        "entity": ["guest", "guests"],
        "cast": ["Mabel", "Priya"],
        "question": {"text": "Who tucked the cameo away?", "cat": "Book", "value": "almanac"},
        "cats": [
            {"label": "Guest", "kind": "name", "values": ["Mabel", "Zeke", "Carmen", "Ivan", "Basil"]},
            {"label": "Drink", "values": ["cocoa", "cider", "tea", "coffee", "eggnog"],
             "ref": "the {v} drinker",
             "pred": "drank {v}",
             "neg": "did not drink {v}",
             "either": "drank either {a} or {b}",
             "nor": "drank neither {a} nor {b}",
             "short": "the {v}"},
            {"label": "Book", "values": ["almanac", "sea stories", "poems", "cookbook", "mystery"],
             "ref": "the reader of the {v}",
             "pred": "read the {v}",
             "neg": "did not read the {v}",
             "either": "read either the {a} or the {b}",
             "nor": "read neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Time", "ordered": True,
             "nums": [840, 860, 880, 900, 920],
             "labels": ["2:00 p.m.", "2:20 p.m.", "2:40 p.m.", "3:00 p.m.", "3:20 p.m."],
             "ref": "the guest who sat down at {x}",
             "pred": "sat down at {x}",
             "neg": "did not sit down at {x}",
             "either": "sat down at either {a} or {b}",
             "nor": "sat down at neither {a} nor {b}",
             "short": "{x}",
             "more": "sat down later than {y}",
             "less": "sat down earlier than {y}",
             "dmore": "sat down exactly {d} after {y}",
             "dless": "sat down exactly {d} before {y}",
             "dunit": ["minute", "minutes"],
             "dmore1": "sat down 20 minutes after {y}",
             "dless1": "sat down 20 minutes before {y}"},
        ],
    },
]
