"""Chapter 6, part 2: Case Files (November), puzzles 88-95.

All eight slots are "suppose" cases: five people, three categories, one of
them ordered (a time, a cost, a shift length or an age). Each case has a
whodunit question; the culprit value comes from the story evidence in the
bible. None of these answers is forced except #91 (Hugo).
Times are written as minutes after midnight so that "exactly 60 minutes
after" comes out right; prices in dollars; shifts in hours; ages in years.
Format: THEMES.md.  Story and cast: story/bible.md, section 6.
"""

THEMES = [
    # ------------------------------------------------------------------ 88
    {
        "slot": 88,
        "title": "The Case of the Fast Clock",
        "story": "Jonah sets his watch by the big clock over the ferry dock, so when someone nudged it "
                 "ten minutes fast, the ferry left early and stranded the town moderator on the dock, "
                 "briefcase in hand. The clock hangs too high to reach without something to stand on. "
                 "Five people came by the dock the evening before, each carrying something different "
                 "and wearing a different hat. Who set the clock ahead?",
        "entity": ["visitor", "visitors"],
        "cast": ["Rosa", "Otis", "Jonah"],
        "question": {"text": "Who set the dock clock fast?", "cat": "Carried", "value": "step stool"},
        "cats": [
            {"label": "Visitor", "kind": "name", "values": ["Amara", "Rosa", "Kit", "Vito", "Otis"]},
            {"label": "Carried", "values": ["toolbox", "umbrella", "basket", "lantern", "step stool"],
             "ref": "the person with the {v}",
             "pred": "carried the {v}",
             "neg": "did not carry the {v}",
             "either": "carried either the {a} or the {b}",
             "nor": "carried neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Hat", "values": ["beret", "cap", "beanie", "fedora", "bonnet"],
             "ref": "the person in the {v}",
             "pred": "wore the {v}",
             "neg": "did not wear the {v}",
             "either": "wore either the {a} or the {b}",
             "nor": "wore neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Time", "ordered": True,
             "nums": [1080, 1110, 1140, 1170, 1200],
             "labels": ["6:00 p.m.", "6:30 p.m.", "7:00 p.m.", "7:30 p.m.", "8:00 p.m."],
             "ref": "the {x} visitor",
             "pred": "came by at {x}",
             "neg": "did not come by at {x}",
             "either": "came by at either {a} or {b}",
             "nor": "came by at neither {a} nor {b}",
             "short": "{x}",
             "more": "came by later than {y}",
             "less": "came by earlier than {y}",
             "dmore": "came by exactly {d} after {y}",
             "dless": "came by exactly {d} before {y}",
             "dunit": ["minute", "minutes"],
             "dmore1": "came by half an hour after {y}",
             "dless1": "came by half an hour before {y}"},
        ],
    },
    # ------------------------------------------------------------------ 89
    {
        "slot": 89,
        "title": "The Case of the Short Cash Box",
        "story": "At the holiday craft fair on the Saturday after Thanksgiving, the cash box came up "
                 "exactly twenty dollars short, and Hattie has added \"find twenty dollars\" to her list of "
                 "lists. Nobody suspects a thief, only a slip of the fingers: the box sat on the cocoa "
                 "table all day, and only the cocoa volunteer made change from it. Five volunteers each "
                 "ran a different table for a different number of hours. Who made the wrong change?",
        "entity": ["volunteer", "volunteers"],
        "cast": ["Hattie"],
        "question": {"text": "Who made the wrong change?", "cat": "Table", "value": "cocoa"},
        "cats": [
            {"label": "Volunteer", "kind": "name", "values": ["Una", "Ruben", "Hattie", "Dev", "Elsa"]},
            {"label": "Table", "values": ["cocoa", "candles", "wreaths", "mittens", "fudge"],
             "ref": "the volunteer who sold {v}",
             "pred": "sold {v}",
             "neg": "did not sell {v}",
             "either": "sold either {a} or {b}",
             "nor": "sold neither {a} nor {b}",
             "short": "the {v} table"},
            {"label": "Name tag", "values": ["holly", "star", "snowman", "reindeer", "pinecone"],
             "ref": "the volunteer with the {v} name tag",
             "pred": "wore the {v} name tag",
             "neg": "did not wear the {v} name tag",
             "either": "wore either the {a} or the {b} name tag",
             "nor": "wore neither the {a} nor the {b} name tag",
             "short": "the {v} tag"},
            {"label": "Shift", "ordered": True,
             "nums": [1, 2, 3, 4, 5],
             "labels": ["1 hour", "2 hours", "3 hours", "4 hours", "5 hours"],
             "ref": "the volunteer who worked {x}",
             "pred": "worked {x}",
             "neg": "did not work {x}",
             "either": "worked either {a} or {b}",
             "nor": "worked neither {a} nor {b}",
             "short": "{x}",
             "more": "worked longer than {y}",
             "less": "worked a shorter shift than {y}",
             "dmore": "worked exactly {d} longer than {y}",
             "dless": "worked exactly {d} less than {y}",
             "dunit": ["hour", "hours"],
             "dmore1": "worked one hour longer than {y}",
             "dless1": "worked one hour less than {y}"},
        ],
    },
    # ------------------------------------------------------------------ 90
    {
        "slot": 90,
        "title": "The Case of the Painted Buoys",
        "story": "Nico woke to find his orange lobster buoys painted a bright, cheerful purple, and now "
                 "nobody on the pier can tell whose traps are whose. He swears you can see them from "
                 "Portugal. Gus remembers selling paint to five customers at Mahoney's this week, and "
                 "exactly one can of purple, but his famous knee forecasts rain, not faces. Who turned "
                 "Nico's buoys purple?",
        "entity": ["customer", "customers"],
        "cast": ["Felix", "Nico", "Gus"],
        "question": {"text": "Who painted the buoys?", "cat": "Paint", "value": "purple"},
        "cats": [
            {"label": "Customer", "kind": "name", "values": ["Enzo", "Della", "Yusuf", "Marta", "Felix"]},
            {"label": "Paint", "values": ["purple", "teal", "white", "black", "yellow"],
             "ref": "the buyer of the {v} paint",
             "pred": "bought the {v} paint",
             "neg": "did not buy the {v} paint",
             "either": "bought either the {a} or the {b} paint",
             "nor": "bought neither the {a} nor the {b} paint",
             "short": "the {v} paint"},
            {"label": "Brush", "values": ["roller", "sponge", "wide brush", "spray can", "rag"],
             "ref": "the customer with the {v}",
             "pred": "picked up the {v}",
             "neg": "did not pick up the {v}",
             "either": "picked up either the {a} or the {b}",
             "nor": "picked up neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Cost", "ordered": True,
             "nums": [8, 10, 12, 14, 16],
             "labels": ["$8", "$10", "$12", "$14", "$16"],
             "ref": "the customer who spent {x}",
             "pred": "spent {x}",
             "neg": "did not spend {x}",
             "either": "spent either {a} or {b}",
             "nor": "spent neither {a} nor {b}",
             "short": "{x}",
             "more": "spent more than {y}",
             "less": "spent less than {y}",
             "dmore": "spent exactly {d} more than {y}",
             "dless": "spent exactly {d} less than {y}",
             "dunit": ["dollar", "dollars"],
             "dmore1": "spent two dollars more than {y}",
             "dless1": "spent two dollars less than {y}"},
        ],
    },
    # ------------------------------------------------------------------ 91
    {
        "slot": 91,
        "title": "The Case of the Lantern Room",
        "story": "Lena has two puzzles. The old one: since early November, the Keeper's Lamp's brass has "
                 "shone as if someone polished it, and none of her volunteers did. The new one: muddy "
                 "footprints on the spiral stair on Wednesday morning, though it was spotless when the "
                 "museum closed at a quarter to six on Tuesday. Five people climbed the tower on Tuesday, "
                 "each stopping at a different landing with something different in hand. Who went back up "
                 "after closing time?",
        "entity": ["climber", "climbers"],
        "cast": ["Jonah", "Wren", "Teddy", "Lena"],
        "question": {"text": "Who climbed the tower after closing?", "cat": "Time", "value": "6:00 p.m."},
        "answer": "Hugo",
        "cats": [
            {"label": "Climber", "kind": "name", "values": ["Hugo", "Jonah", "Wren", "Teddy", "Cass"]},
            {"label": "Item", "values": ["sketchbook", "thermos", "field guide", "flashlight", "notebook"],
             "ref": "the climber with the {v}",
             "pred": "carried the {v}",
             "neg": "did not carry the {v}",
             "either": "carried either the {a} or the {b}",
             "nor": "carried neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Landing", "values": ["1st landing", "2nd landing", "3rd landing", "4th landing", "top"],
             "ref": "the climber who stopped at the {v}",
             "pred": "stopped at the {v}",
             "neg": "did not stop at the {v}",
             "either": "stopped at either the {a} or the {b}",
             "nor": "stopped at neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Time", "ordered": True,
             "nums": [960, 990, 1020, 1050, 1080],
             "labels": ["4:00 p.m.", "4:30 p.m.", "5:00 p.m.", "5:30 p.m.", "6:00 p.m."],
             "ref": "the {x} climber",
             "pred": "climbed at {x}",
             "neg": "did not climb at {x}",
             "either": "climbed at either {a} or {b}",
             "nor": "climbed at neither {a} nor {b}",
             "short": "{x}",
             "more": "climbed later than {y}",
             "less": "climbed earlier than {y}",
             "dmore": "climbed exactly {d} after {y}",
             "dless": "climbed exactly {d} before {y}",
             "dunit": ["minute", "minutes"],
             "dmore1": "climbed half an hour after {y}",
             "dless1": "climbed half an hour before {y}"},
        ],
    },
    # ------------------------------------------------------------------ 92
    {
        "slot": 92,
        "title": "The Case of the Jammed Press",
        "story": "Press night at the Gazette was going beautifully until the old press groaned, clanked "
                 "and stopped dead, and Ada pulled a single red mitten out of the rollers. The press room "
                 "is drafty in November, so the five helpers, on five different jobs, all worked in "
                 "mittens, each pair a different color. In forty-one years Ada has fished a necktie and "
                 "half a sandwich out of that press, but never a mitten. Whose mitten stopped the press?",
        "entity": ["helper", "helpers"],
        "cast": [],
        "question": {"text": "Whose mitten jammed the press?", "cat": "Mittens", "value": "red"},
        "cats": [
            {"label": "Helper", "kind": "name", "values": ["Selma", "Quinn", "Milo", "Imani", "Greta"]},
            {"label": "Mittens", "values": ["red", "gray", "green", "white", "brown"],
             "ref": "the helper in {v} mittens",
             "pred": "wore {v} mittens",
             "neg": "did not wear {v} mittens",
             "either": "wore either {a} or {b} mittens",
             "nor": "wore neither {a} nor {b} mittens",
             "short": "the {v} mittens"},
            {"label": "Job", "values": ["folding", "inking", "bundling", "sweeping", "proofing"],
             "ref": "the helper who did the {v}",
             "pred": "did the {v}",
             "neg": "did not do the {v}",
             "either": "did either the {a} or the {b}",
             "nor": "did neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Time", "ordered": True,
             "nums": [1200, 1220, 1240, 1260, 1280],
             "labels": ["8:00 p.m.", "8:20 p.m.", "8:40 p.m.", "9:00 p.m.", "9:20 p.m."],
             "ref": "the {x} arrival",
             "pred": "came in at {x}",
             "neg": "did not come in at {x}",
             "either": "came in at either {a} or {b}",
             "nor": "came in at neither {a} nor {b}",
             "short": "{x}",
             "more": "came in later than {y}",
             "less": "came in earlier than {y}",
             "dmore": "came in exactly {d} after {y}",
             "dless": "came in exactly {d} before {y}",
             "dunit": ["minute", "minutes"],
             "dmore1": "came in twenty minutes after {y}",
             "dless1": "came in twenty minutes before {y}"},
        ],
    },
    # ------------------------------------------------------------------ 93
    {
        "slot": 93,
        "title": "The Case of the Bottled Ship",
        "story": "On Monday morning the library's prized ship in a bottle, the *Constance*, was gone from "
                 "its glass case. In its place sat a short length of rope tied in a neat bowline, borrowed "
                 "from the knots display. Over the weekend, five volunteers each dusted one display with a "
                 "different duster, and Wren whispers that she would like her ship back before story "
                 "hour, please. Who moved the ship in a bottle?",
        "entity": ["volunteer", "volunteers"],
        "cast": ["Otis", "Wren"],
        "question": {"text": "Who moved the ship in a bottle?", "cat": "Display", "value": "knots"},
        "cats": [
            {"label": "Volunteer", "kind": "name", "values": ["Faye", "Otis", "Cyrus", "Bea", "Jade"]},
            {"label": "Display", "values": ["maps", "anchors", "shells", "lanterns", "knots"],
             "ref": "the volunteer who dusted the {v}",
             "pred": "dusted the {v}",
             "neg": "did not dust the {v}",
             "either": "dusted either the {a} or the {b}",
             "nor": "dusted neither the {a} nor the {b}",
             "short": "the {v} display"},
            {"label": "Duster", "values": ["chamois", "cloth", "brush", "mitt", "wand"],
             "ref": "the volunteer with the {v}",
             "pred": "dusted with the {v}",
             "neg": "did not dust with the {v}",
             "either": "dusted with either the {a} or the {b}",
             "nor": "dusted with neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Age", "ordered": True,
             "nums": [35, 45, 55, 65, 75],
             "ref": "the {x}-year-old",
             "pred": "is {x} years old",
             "neg": "is not {x} years old",
             "either": "is either {a} or {b} years old",
             "nor": "is neither {a} nor {b} years old",
             "short": "age {x}",
             "more": "is older than {y}",
             "less": "is younger than {y}",
             "dmore": "is exactly {d} older than {y}",
             "dless": "is exactly {d} younger than {y}",
             "dunit": ["year", "years"],
             "dmore1": "is ten years older than {y}",
             "dless1": "is ten years younger than {y}"},
        ],
    },
    # ------------------------------------------------------------------ 94
    {
        "slot": 94,
        "title": "The Case of the Leaky Rowboat",
        "story": "Someone pulled the drain plug on the boatyard's work rowboat, one of the last boats "
                 "still in the water, and it sank gently into two feet of water at the slip. Felix is "
                 "fuming, politely. The plug turned up at the bottom of a bailing bucket left on the "
                 "dock, and five people were at the slips that afternoon, each hauling a different boat "
                 "out for the winter. Who pulled the plug?",
        "entity": ["boat owner", "boat owners"],
        "cast": ["Nico", "Priya", "Felix"],
        "question": {"text": "Who pulled the plug?", "cat": "Gear", "value": "bucket"},
        "cats": [
            {"label": "Owner", "kind": "name", "values": ["Kenji", "Nico", "Priya", "Hal", "Una"]},
            {"label": "Boat", "values": ["skiff", "kayak", "canoe", "dory", "punt"],
             "ref": "the {v}'s owner",
             "pred": "hauled out the {v}",
             "neg": "did not haul out the {v}",
             "either": "hauled out either the {a} or the {b}",
             "nor": "hauled out neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Gear", "values": ["oars", "net", "cooler", "anchor", "bucket"],
             "ref": "the person with the {v}",
             "pred": "brought the {v}",
             "neg": "did not bring the {v}",
             "either": "brought either the {a} or the {b}",
             "nor": "brought neither the {a} nor the {b}",
             "short": "the {v}"},
            {"label": "Time", "ordered": True,
             "nums": [780, 795, 810, 825, 840],
             "labels": ["1:00 p.m.", "1:15 p.m.", "1:30 p.m.", "1:45 p.m.", "2:00 p.m."],
             "ref": "the person who arrived at {x}",
             "pred": "arrived at {x}",
             "neg": "did not arrive at {x}",
             "either": "arrived at either {a} or {b}",
             "nor": "arrived at neither {a} nor {b}",
             "short": "{x}",
             "more": "arrived later than {y}",
             "less": "arrived earlier than {y}",
             "dmore": "arrived exactly {d} after {y}",
             "dless": "arrived exactly {d} before {y}",
             "dunit": ["minute", "minutes"],
             "dmore1": "arrived a quarter of an hour after {y}",
             "dless1": "arrived a quarter of an hour before {y}"},
        ],
    },
    # ------------------------------------------------------------------ 95
    {
        "slot": 95,
        "title": "The Case of the Midnight Ovens",
        "story": "Four a.m. is Rosa's hour, so she was startled to find her ovens already warm and a tray "
                 "of gingerbread lighthouses cooling on the rack, each with a tiny icing lamp. Five "
                 "friends know where she hides the bakery's spare key, and each has a different baking "
                 "specialty. The icing, Rosa admits, is very nearly as good as hers. Who baked at "
                 "midnight?",
        "entity": ["baker", "bakers"],
        "cast": ["Mabel", "Gus", "Rosa"],
        "question": {"text": "Who baked at midnight?", "cat": "Treat", "value": "gingerbread"},
        "cats": [
            {"label": "Baker", "kind": "name", "values": ["Emil", "Ruben", "Mabel", "Lou", "Gus"]},
            {"label": "Apron", "values": ["blue", "flowered", "plaid", "white", "striped"],
             "ref": "the baker in the {v} apron",
             "pred": "bakes in the {v} apron",
             "neg": "does not bake in the {v} apron",
             "either": "bakes in either the {a} or the {b} apron",
             "nor": "bakes in neither the {a} nor the {b} apron",
             "short": "the {v} apron"},
            {"label": "Treat", "values": ["gingerbread", "biscotti", "brownies", "rolls", "fudge"],
             "ref": "the baker known for {v}",
             "pred": "is known for {v}",
             "neg": "is not known for {v}",
             "either": "is known for either {a} or {b}",
             "nor": "is known for neither {a} nor {b}",
             "short": "{v}"},
            {"label": "Age", "ordered": True,
             "nums": [60, 65, 70, 75, 80],
             "ref": "the {x}-year-old",
             "pred": "is {x} years old",
             "neg": "is not {x} years old",
             "either": "is either {a} or {b} years old",
             "nor": "is neither {a} nor {b} years old",
             "short": "age {x}",
             "more": "is older than {y}",
             "less": "is younger than {y}",
             "dmore": "is exactly {d} older than {y}",
             "dless": "is exactly {d} younger than {y}",
             "dunit": ["year", "years"],
             "dmore1": "is five years older than {y}",
             "dless1": "is five years younger than {y}"},
        ],
    },
]
