"""Glossary entries (term, definition) — LaTeX text."""

GLOSSARY = [
    ("Absolute value", r"The distance of a number from 0 on the number line; never negative. $|-7| = 7$."),
    ("Acute angle", r"An angle greater than $0^\circ$ and less than $90^\circ$."),
    ("Area", r"The amount of surface a flat figure covers, measured in square units."),
    ("Average (mean)", r"The sum of a set of values divided by the number of values."),
    ("Binomial", r"A polynomial with two terms, such as $x + 5$."),
    ("Circumference", r"The distance around a circle: $C = 2\pi r = \pi d$."),
    ("Coefficient", r"The number multiplying a variable. In $7x^2$, the coefficient is 7."),
    ("Complementary angles", r"Two angles whose measures add up to $90^\circ$."),
    ("Composite number", r"A whole number greater than 1 that has more than two factors, such as 9 or 12."),
    ("Congruent", r"Having exactly the same size and shape (equal sides, equal angles)."),
    ("Consecutive integers", r"Integers that follow one another in order, such as 7, 8, 9."),
    ("Constant", r"A term with no variable, such as the 5 in $3x + 5$."),
    ("Denominator", r"The bottom number of a fraction; it tells how many equal parts make a whole."),
    ("Diameter", r"A segment through the center of a circle from side to side; twice the radius."),
    ("Difference", r"The result of a subtraction."),
    ("Digit", r"Any of the symbols 0--9 used to write numbers."),
    ("Divisor", r"The number you divide by. In $20 \div 4$, the divisor is 4."),
    ("Equation", r"A statement that two expressions are equal, such as $2x + 3 = 11$."),
    ("Equilateral triangle", r"A triangle with three equal sides and three $60^\circ$ angles."),
    ("Even number", r"An integer divisible by 2."),
    ("Exponent", r"The small raised number that tells how many times the base is used as a factor: $2^3 = 2\cdot2\cdot2$."),
    ("Factor", r"A number that divides another number evenly. The factors of 12 are 1, 2, 3, 4, 6, 12."),
    ("Greatest common factor (GCF)", r"The largest number that divides each of two or more numbers."),
    ("Hypotenuse", r"The longest side of a right triangle, opposite the right angle."),
    ("Improper fraction", r"A fraction whose numerator is greater than or equal to its denominator, such as $\frac74$."),
    ("Inequality", r"A statement using $<$, $>$, $\le$, or $\ge$ to compare two expressions."),
    ("Integer", r"A whole number or its opposite: $\ldots, -2, -1, 0, 1, 2, \ldots$"),
    ("Irrational number", r"A number that cannot be written as a fraction of integers, such as $\sqrt2$ or $\pi$."),
    ("Isosceles triangle", r"A triangle with at least two equal sides; the angles opposite them are equal."),
    ("Least common multiple (LCM)", r"The smallest positive number that is a multiple of each of two or more numbers."),
    ("Like terms", r"Terms with the same variables raised to the same powers, such as $3x^2$ and $-5x^2$."),
    ("Linear equation", r"An equation whose graph is a straight line; the variable has no exponent above 1."),
    ("Median", r"The middle value of a sorted list (or the average of the two middle values)."),
    ("Mixed number", r"A whole number and a fraction together, such as $2\frac13$."),
    ("Mode", r"The value that occurs most often in a data set."),
    ("Monomial", r"A polynomial with one term, such as $-4x^3y$."),
    ("Multiple", r"The product of a number and a whole number. Multiples of 6: 6, 12, 18, \ldots"),
    ("Numerator", r"The top number of a fraction."),
    ("Obtuse angle", r"An angle greater than $90^\circ$ and less than $180^\circ$."),
    ("Odd number", r"An integer that is not divisible by 2."),
    ("Parallel lines", r"Lines in the same plane that never meet; they have equal slopes."),
    ("Percent", r"Per hundred: $35\% = \frac{35}{100} = 0.35$."),
    ("Perimeter", r"The distance around a figure."),
    ("Perpendicular lines", r"Lines that meet at a right angle; their slopes are negative reciprocals."),
    ("Polygon", r"A closed figure made of straight sides (triangle, quadrilateral, pentagon, \ldots)."),
    ("Polynomial", r"A sum of terms of the form $ax^n$, such as $3x^2 - 5x + 2$."),
    ("Prime number", r"A whole number greater than 1 whose only factors are 1 and itself: 2, 3, 5, 7, 11, \ldots"),
    ("Probability", r"The chance that an event occurs, from 0 (impossible) to 1 (certain)."),
    ("Product", r"The result of a multiplication."),
    ("Proportion", r"An equation stating that two ratios are equal, such as $\frac{3}{4} = \frac{9}{12}$."),
    ("Quadrant", r"One of the four regions of the coordinate plane, numbered I--IV counterclockwise from the upper right."),
    ("Quadratic equation", r"An equation of the form $ax^2 + bx + c = 0$ with $a \ne 0$."),
    ("Quotient", r"The result of a division."),
    ("Radius", r"The distance from the center of a circle to any point on it."),
    ("Range", r"The difference between the largest and smallest values in a data set."),
    ("Ratio", r"A comparison of two quantities by division, written $3:4$ or $\frac34$."),
    ("Rational number", r"Any number that can be written as a fraction of two integers."),
    ("Reciprocal", r"The number that multiplies with a given number to give 1. The reciprocal of $\frac23$ is $\frac32$."),
    ("Right angle", r"An angle of exactly $90^\circ$."),
    ("Scientific notation", r"A number written as $a \times 10^n$ with $1 \le a < 10$, such as $4.2 \times 10^5$."),
    ("Slope", r"The steepness of a line: rise over run, $\frac{y_2 - y_1}{x_2 - x_1}$."),
    ("Square root", r"A number that, multiplied by itself, gives the original number: $\sqrt{49} = 7$."),
    ("Sum", r"The result of an addition."),
    ("Supplementary angles", r"Two angles whose measures add up to $180^\circ$."),
    ("Trinomial", r"A polynomial with three terms, such as $x^2 + 5x + 6$."),
    ("Variable", r"A letter that stands for an unknown or changing number."),
    ("Vertex", r"A corner point of an angle, polygon, or solid (plural: vertices)."),
    ("Vertical angles", r"The opposite angles formed by two intersecting lines; they are equal."),
    ("Volume", r"The amount of space a solid occupies, measured in cubic units."),
    ("Whole numbers", r"The numbers 0, 1, 2, 3, \ldots"),
]
