"""Merge the two candidate lists into data/verse_pool.json (the book's 7 parts).

    python3 -m bc.pool

Sources (references only, never verse text):
  data/verse_pool_agent.json  - 323 passages in 14 themes, with popularity 1-3 (Claude's editorial judgement)
  data/verse_pool_extra.json  - supplementary passages, including exact fragments of long verses
Within a part, candidates are ranked by popularity (passages proposed by both lists get a bonus)
and interleaved across the source themes so a part does not read like one chapter.
"""
from __future__ import annotations

import collections
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")

PARTS = [
    ("Comfort in Hard Times", 32, ["Comfort in Hard Times", "The Lord Is My Shepherd"]),
    ("Peace for an Anxious Heart", 26, ["Peace", "Prayer", "Peace for an Anxious Heart"]),
    ("Hope That Does Not Fade", 30, ["Hope", "God's Promises & Eternal Life", "Easter & Resurrection", "Hope That Does Not Fade"]),
    ("Strength & Courage", 30, ["Strength & Courage"]),
    ("Faith & Trust", 30, ["Faith & Trust", "Wisdom & Guidance", "Words of Jesus"]),
    ("Love, Joy & Praise", 30, ["God's Love & Grace", "Joy, Praise & Thanksgiving", "God's Love & Joy"]),
    ("Christmas: Good Tidings of Great Joy", 22, ["Christmas & the Nativity", "Christmas: Good Tidings of Great Joy"]),
]
# Pieces of one longer passage that read oddly on their own, and passages flagged for review.
EXCLUDE = {"Matthew 6:9-10", "Matthew 6:11-12", "Matthew 6:13", "2 Chronicles 7:14", "Song of Solomon 2:11-12",
           "Psalms 18:39", "Zechariah 9:9",
           "Psalms 23:1-2", "Psalms 23:1",   # Psalm 23:1 is the worked example in "How to Solve"
           # final review: near-duplicates, weak theme fits, verses ending on a comma
           "Exodus 15:2", "Psalms 118:14", "Deuteronomy 31:8", "Psalms 31:24", "Matthew 1:23",
           "Proverbs 15:1", "Proverbs 17:17", "Romans 12:18", "John 13:34-35", "Titus 2:11", "1 Peter 1:3",
           # used only as the exact fragments listed in verse_pool_extra.json
           "Hebrews 6:19", "Psalms 30:5", "Matthew 2:11", "Isaiah 9:6",
           # Christmas: room for the shepherds, Mary pondering and both halves of Isaiah 9:6
           "Isaiah 40:5", "1 John 4:9"}
# Must-have passages ranked above everything else in their part.
BOOST = {"Luke 2:7": 6, "Luke 2:13-14": 6, "Luke 2:10-11": 6}


def main():
    agent = json.load(open(os.path.join(DATA, "verse_pool_agent.json")))
    extra = json.load(open(os.path.join(DATA, "verse_pool_extra.json")))
    in_agent = {r["ref"] for t in agent["themes"] for r in t["refs"]}
    in_extra = {r["ref"] for t in extra["themes"] for r in t["refs"]}
    part_of = {src: name for name, _, srcs in PARTS for src in srcs}
    cands = collections.defaultdict(list)
    for origin, pool in (("agent", agent), ("extra", extra)):
        for t in pool["themes"]:
            part = part_of[t["theme"]]
            for rank, r in enumerate(t["refs"]):
                if (r["ref"] in EXCLUDE and not (r.get("from") or r.get("to"))) or r.get("caution"):
                    continue
                pop = r.get("popularity", 2) + (0.5 if r["ref"] in in_agent and r["ref"] in in_extra else 0)
                pop = max(pop, BOOST.get(r["ref"], 0))
                cands[part].append(dict(r, popularity=pop, _src=t["theme"], _rank=rank, _origin=origin))
    out = {"note": "Generated by bc.pool from verse_pool_agent.json + verse_pool_extra.json; edit those.", "themes": []}
    for name, quota, _ in PARTS:
        seen, items = set(), []
        for c in sorted(cands[name], key=lambda c: (-c["popularity"], c["_rank"], c["_origin"] != "agent")):
            key = (c["ref"], c.get("from"), c.get("to"))
            if key in seen:
                continue
            seen.add(key)
            items.append({k: v for k, v in c.items() if not k.startswith("_")})
        entry = {"theme": name, "quota": quota, "intro": "", "refs": items}
        if name.startswith("Christmas"):
            entry["max_per_chapter"] = 6     # the story lives in Luke 2 and Matthew 2
        out["themes"].append(entry)
    with open(os.path.join(DATA, "verse_pool.json"), "w") as f:
        json.dump(out, f, indent=1)
        f.write("\n")
    for t in out["themes"]:
        print(f"{t['theme']:40s} quota {t['quota']:3d} candidates {len(t['refs'])}")


if __name__ == "__main__":
    main()
