"""Choose the book's verses from the candidate pool -> data/selection.json.

    python3 -m bc.select

Input: data/verse_pool.json (bc.pool).  Every candidate's text is looked up in the five
KJV copies.  Part by part, candidates are taken in pool order (most popular first) until
the part's quota is reached.  A candidate is skipped when
  * fewer than 4 of the 5 copies agree on its letters,
  * it needs fewer than MIN_LINES or more than MAX_LINES lines on the page,
  * it shares a verse with a passage already chosen (also inside ranges),
  * its chapter already has MAX_PER_CHAPTER passages in this part.
Levels are assigned later, in bc.puzzles.
"""
from __future__ import annotations

import collections
import json
import os
import sys

from . import cipher, kjv, layout

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")
MAX_PER_CHAPTER = 3


def check(c: dict):
    """-> (info dict, None) or (None, reason)"""
    ref = c["ref"]
    try:
        book, ch, v1, v2 = kjv.parse_ref(ref)
        p = kjv.passage(ref, c.get("from"), c.get("to"))
    except (KeyError, ValueError) as e:
        return None, f"not found: {e}"
    agree = min(len(x["letters_agree"]) + len(x["title_prefixed"]) for x in p["parts"])
    if agree < 4:
        return None, f"only {agree}/5 copies agree"
    lines = layout.lines_needed(cipher.encrypt(p["text"], cipher.make_key(ref)))
    if lines < layout.MIN_LINES:
        return None, f"too short ({lines} lines)"
    if lines > layout.MAX_LINES:
        return None, f"too long ({lines} lines)"
    if p["partial"]:
        a = p["full_text"].index(p["text"])
        keys = {(book, ch, v1, "chars", i) for i in range(a, a + len(p["text"]))}
    else:
        keys = {(book, ch, v) for v in range(v1, v2 + 1)}
    return {"keys": keys, "verses": {(book, ch, v) for v in range(v1, v2 + 1)}, "partial": p["partial"], "chapter": (book, ch),
            "letters": len(kjv.letters(p["text"])), "lines": lines}, None


def main():
    pool = json.load(open(os.path.join(DATA, "verse_pool.json")))
    used: set[tuple] = set()
    used_part: set[tuple] = set()
    chosen, dropped, spare = [], [], []
    for t in pool["themes"]:
        per_chapter = collections.Counter()
        mine = []
        for c in t["refs"]:
            if len(mine) >= t["quota"]:
                spare.append((t["theme"], c["ref"]))
                continue
            info, why = check(c)
            if info is None:
                dropped.append((c["ref"], why))
                continue
            if info["keys"] & used:
                continue
            # a whole verse and a fragment of it never appear together
            if (not info["partial"] and info["verses"] & used_part) or (info["partial"] and info["verses"] & used):
                continue
            if per_chapter[info["chapter"]] >= t.get("max_per_chapter", MAX_PER_CHAPTER):
                spare.append((t["theme"], c["ref"] + " (chapter limit)"))
                continue
            used |= info["keys"]
            if info["partial"]:
                used_part |= info["verses"]
            per_chapter[info["chapter"]] += 1
            mine.append({k: v for k, v in (("ref", c["ref"]), ("from", c.get("from")), ("to", c.get("to")),
                                             ("theme", t["theme"])) if v})
        if len(mine) < t["quota"]:
            print(f"warning: {t['theme']}: only {len(mine)} of {t['quota']}", file=sys.stderr)
        chosen.extend(mine)
    sel = {"themes": [{"name": t["theme"], "intro": t.get("intro", "")} for t in pool["themes"]], "puzzles": chosen}
    with open(os.path.join(DATA, "selection.json"), "w") as f:
        json.dump(sel, f, indent=1)
        f.write("\n")
    with open(os.path.join(DATA, "selection_report.md"), "w") as f:
        f.write("# Verse selection report\n\n")
        f.write(f"Chosen: {len(chosen)}. Generated by `python3 -m bc.select`.\n\n## Not usable\n\n")
        for r, why in sorted(set(dropped)):
            f.write(f"- {r}: {why}\n")
        f.write("\n## Usable spares (not needed to fill the quota)\n\n")
        for th, r in spare:
            f.write(f"- {th}: {r}\n")
    print(f"chosen {len(chosen)} ({len(set(dropped))} unusable)", file=sys.stderr)


if __name__ == "__main__":
    main()
